version: "3.1"
services:
  mysql:
    container_name: communicraftDB
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - "3307:3306"
    healthcheck:
      timeout: 20s
      retries: 10
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  app:
    image: communicraft
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

    depends_on:
      mysql:
        condition: service_healthy
